---
title: "Summary of Paper"
output:
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 1
    #code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
```

This is a summary of the paper entitled 
"Uh and euh signal novelty for monolinguals and bilinguals: evidence from children and adults" by 
Elizabeth Morin-Lessard and Krista Byers-Heinlein (doi: 10.1017/S0305000918000612)

#Introduction
Hesitation markers and disfluencies such as the English “uh” and “um” are often utilized before new or unfamiliar words or clauses, and then can be used by listeners to predict when the speaker will be referring to something difficult to name and potentially novel (either entirely, or in the discourse), though the basis of this prediction is not clear. These disfluencies differ based on the language and may root from the vowel form of the common determiners in the language, such as the “uh” sound potentially emerging from “the”. Because the occurrence of these speech disfluencies is predictable, they are often used as cues when processing natural speech. Research demonstrates that disfluencies are used by children in comprehension, as seen by how when disfluencies were used in the introduction of an object, children from 28-32 months looked towards the object before its label was spoken, suggesting a prediction of its novelty. However, this was not seen in children 16-20 months suggesting the ability to use the disfluencies for comprehension and prediction appeared during development.  Further research has revealed the development of this ability, and the beginning of its flexible adaptation to different speakers and contexts, around two years of age.

This study examined further the question of why speech disfluencies are so useful for processing in both children and adults, both bilingual and monolingual speakers. One idea is that natural sensitivity to statistical regularities in language allows children to learn through experience about the predictive use of these disfluencies before novelties, either entirely or in the discourse. Thus, after sufficient experience, children would be able to use typical and frequently heard disfluencies to make predictions about what will appear in the sentence, but would be unable or less able to do so using disfluencies that are foreign or atypical to them. Another potential idea is that it is not the word itself, but rather the lengthening that often accompanies disfluencies that children learn is a marker for novelty or uncertainty, in which case, both native and foreign disfluencies should function equally as cues for what is to follow in the sentence. The unique experience of bilinguals, who would hear two different sets of disfluencies for the two different languages, sometimes even utilized in a manner where the language of the disfluency is incongruous with the rest of the sentence, could provide insight as to the development of this predictive ability though disfluencies. If the typicality and familiarity with disfluencies is important in their predictive utilization, then bilinguals might develop this ability later because of their reduced experience with distinctly either set of disfluencies compared to a monolingual.

Therefore, the main goal of this study was to research how disfluencies are able to act as predictors of speech by comparing listeners from two different backgrounds, English-speaking and French-speaking, who have either monolingual or bilingual experiences. Two separate studies were done, with 32 month old children, and with adults, in order to also add the perspective of development into the research. The studies were conducted using a preferential looking paradigm. First, English and French monolingual children were tested on their predictive utilization of disfluencies both congruent and incongruent with their native language in order to test whether only native-like disfluencies could be predictively utilized. Then bilingual English/French children and adults were tested on their comprehension of language congruent or language incongruent disfluencies. The hypothesis overall was consistent with the previously mentioned first idea, in which the ability to use disfluencies as a predictor for what is to come develops through experience with them, which would result in differences based on the language of the disfluency and the listener’s background as monolingual or bilingual.

#Methodology
In the first study with children, an eye-tracker was used to present the visual stimuli, consisting of 32 image pairs of familiar/novel objects appearing on a white background of a 24-inch screen. Each object label was presented three times. The first time, the familiar object was used in either an English or French sentence. In the second trial, the familiar object was names in a different sentence. In the third trial, either the familiar or novel object was named, and half of the trials were fluent while the other half were disfluent. In the disfluent trials, half the trials used disfluencies that were language congruent, while the other half used language incongruent disfluencies. In the third trial, the 2 seconds that were part of the looking prompt before the actual naming of the object were analyzed, and was shifted over by 250 ms to allow children to launch predictive eye movements as they heard a disfluency before hearing the target word. The two seconds encompassed the disfluency of the sentence in the disfluent trials (“Look at thee uh doll” vs “Look at the doll”). Monolingual children were tested in only one language, while bilingual children were tested in both English and French. In the study, the eye tracker was calibrated to the children’s eyes and eye gaze data was collected to determine the proportion of looking to the novel object, found by dividing the total amount of time looking towards the novel object by the total amount of time looking towards the novel or familiar objects. This was the main dependent variable, with Trial Type (Fluent, Disfluent Language-consistent in which the disfluency matched the child’s dominant language, and Disfluent Language-inconsistent in which the disfluency did not match the child’s dominant language) as the independent variable.


#Results
A one way repeated measures ANOVA revealed a significant main effect of Trial Type, and follow up t-tests indicated that the monolingual subjects looked less towards the novel objects in the Fluent trial versus either type of Disfluent trial, and that there was no significant difference in the dependent variable between the Disfluent Language-consistent and Disfluent Language-inconsistent trials. These results agree with and replicate previous findings that indicate monolinguals at the age of 32 months are flexible in their use of disfluencies to predict novelty. ANOVA were also used to confirm that the participants looked towards the novel object once it was named and that there was no significant difficulty in their ability to identify the target in any of the trial types.

The results were similar when the study was repeated with bilinguals, revealing that bilinguals can also equally successfully use disfluencies to predict novelty when the language of the disfluency is both consistent and inconsistent with the rest of the sentence. Bilinguals also showed a marginally significant main effect of Target type (novel or familiar), and follow up t-tests after the initial ANOVA revealed that more time was spent looking at targets with familiar labels than novel labels. Because the label for the object was novel, children had to infer the meaning of the label using a heuristic such as mutual exclusivity, knowing that objects typically only have one label. Thus these results may support previous findings that bilinguals, because they learn two labels for every object, do not use mutual exclusivity to the same degree as their monolingual counterparts. The results between the two trials also indicated that both monolingual and bilingual children successfully utilize disfluency, both language-consistent or language-inconsistent, to predict novelty. These results do not support the initial hypothesis of the researchers, as there was no effect of specific realizations of the disfluency, but instead the children were flexible in its use. One explanation for this is that the “uh” and “euh” sounds were perceived identically, but this is not supported by literature that claims children even much younger can differentiate between small differences in speech sounds. However, it is methodologically challenging to conduct a discrimination task suited for participants of this age (2.5 years) that would be able to confirm this. 

In Study 2 conducted with adults, because of the lack of difference in results with monolingual and bilingual children, only bilingual adults were studied, with sixteen English-French bilingual adults between the ages of 19 to 43 tested. Adults completed a discrimination task first in which they heard the two different languages of disfluencies (“uh” or “euh”) and had to indicate which disfluency they heard, in which they were correct 97.7% of the time. After conducting the experiment, a repeated measures ANOVA revealed a significant effect of Trial type, with no significant difference between the two disfluency trial types, but a lower proportion of looking at the novel object in the Fluent trials as opposed to the Disfluent Language-consistent or Disfluent Language-inconsistent trials. Surprisingly, adults looked towards the novel object below chance across all three trials, but the results still indicated the use of disfluencies to predict novelty. Analysis also confirmed that the participants looked towards the object once it was named, and found that just as in the bilingual children, the adults were more accurate in identifying familiar versus novel target words. The results of this study indicate that bilingual adults can predictively use disfluencies to predict novelty regardless of whether they are consistent or inconsistent with the language of the rest of the sentence, again failing to support the hypothesis and instead showing flexibility in the use of the speech disfluencies, supporting that the use of disfluencies is not achieved by a certain level of experience with them.

#Conclusion
Considerations for further investigation include, besides other testable theories, perhaps that the use of disfluencies to predict novelty may be learned through experience, but that disfluencies are grouped together as speech hesitations in general. Furthermore, the lengthening of the determiner used prior to the hesitation in the trials, which is consistent with how disfluencies are most of the time actually spoken, could also have affected the results and may itself have been a signal for predicting upcoming novelty in the sentence. 

Overall, this study supported the ability of disfluencies to direct attention towards novel objects, and thus the predictive use of disfluencies to indicate novelty. English monolingual, French monolingual and English/French bilingual children are sensitive to characteristics of disfluencies such as the filled pause or lengthening of the determiner, and can thus “flexibly use native, non-native, and code-switched disfluencies to make predictions”. Due to the similarity between the French and English hesitation markers/ disfluencies, further cross language research should be done to further study the extent of this flexibility.
